
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mario
 */
public class quiniela extends javax.swing.JFrame {

    /**
     * Creates new form quiniela
     */
    public quiniela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPtitulos = new javax.swing.JPanel();
        jPotrostitulos = new javax.swing.JPanel();
        jLbpartidos = new javax.swing.JLabel();
        jLbresultados = new javax.swing.JLabel();
        jPtitulo = new javax.swing.JPanel();
        jLbtitulo = new javax.swing.JLabel();
        jPtodo = new javax.swing.JPanel();
        jPartidos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listapartidos = new javax.swing.JList<>();
        jPresultados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLresultados = new javax.swing.JList<>();
        jPbotones = new javax.swing.JPanel();
        jBnuevo = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBrealizarquiniela = new javax.swing.JButton();
        jBresetear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPtitulos.setLayout(new java.awt.BorderLayout());

        jPotrostitulos.setLayout(new java.awt.GridLayout(1, 2));

        jLbpartidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLbpartidos.setText("Partidos");
        jPotrostitulos.add(jLbpartidos);

        jLbresultados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbresultados.setText("Resultados");
        jPotrostitulos.add(jLbresultados);

        jPtitulos.add(jPotrostitulos, java.awt.BorderLayout.CENTER);

        jLbtitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLbtitulo.setForeground(new java.awt.Color(255, 51, 51));
        jLbtitulo.setText("Quiniela");
        jPtitulo.add(jLbtitulo);

        jPtitulos.add(jPtitulo, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPtitulos, java.awt.BorderLayout.PAGE_START);

        jPtodo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPtodo.setLayout(new java.awt.BorderLayout());

        jPartidos.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(listapartidos);

        jPartidos.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPtodo.add(jPartidos, java.awt.BorderLayout.LINE_START);

        jPresultados.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jLresultados);

        jPresultados.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPtodo.add(jPresultados, java.awt.BorderLayout.LINE_END);

        jPbotones.setLayout(new java.awt.GridLayout(4, 1));

        jBnuevo.setText("Nuevo");
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });
        jPbotones.add(jBnuevo);

        jBeliminar.setText("Eliminar");
        jPbotones.add(jBeliminar);

        jBrealizarquiniela.setText("Relizar quiniela");
        jPbotones.add(jBrealizarquiniela);

        jBresetear.setText("Resetear");
        jPbotones.add(jBresetear);

        jPtodo.add(jPbotones, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPtodo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiniela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jBrealizarquiniela;
    private javax.swing.JButton jBresetear;
    private javax.swing.JLabel jLbpartidos;
    private javax.swing.JLabel jLbresultados;
    private javax.swing.JLabel jLbtitulo;
    private javax.swing.JList<String> jLresultados;
    private javax.swing.JPanel jPartidos;
    private javax.swing.JPanel jPbotones;
    private javax.swing.JPanel jPotrostitulos;
    private javax.swing.JPanel jPresultados;
    private javax.swing.JPanel jPtitulo;
    private javax.swing.JPanel jPtitulos;
    private javax.swing.JPanel jPtodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listapartidos;
    // End of variables declaration//GEN-END:variables
}
